---
title: "DATA 607 PROJECT 1"
author: "Matthew Baker"
date: "February 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#incl libraries and import data
```{r}

library(tidyverse)

#read online copy of chess datafile and do some formatting
chesstextread<-readLines("https://raw.githubusercontent.com/mharrisonbaker/CUNYassignments/master/project1/tournamentinfo.txt")
chesstext<-chesstextread[-(1:4)]
chesstext2<- chesstext[seq(1, length(chesstext), 3)]
```


#initialize df and use regex to grab data for columns
```{r}
chessdf <- data.frame("Player's Name", "Player's State", "Total Number of Points", "Player's Pre-Rating", "Average Pre Chess Rating of Opponents")
chessdf <- data.frame()


#name extraction
namepat <- ("([A-Z]+[[:space:]]){2,4}")
name <- unlist(str_extract_all(chesstext, namepat))


#state extraction
statepat <- ("[[:space:]][A-Z]{2}[[:space:]]\\|")
state <- unlist(str_extract_all(chesstext, statepat))
state <- substr(state, 2, 3)



#pre-rating extraction
preratingpat <- c("\\:[[:space:]]{1,2}[[:digit:]]{3,4}")
prerating <- unlist(str_extract_all(chesstext, preratingpat))
prerating<-as.numeric(gsub("\\D", "", prerating))


#total number of points extraction
tpointspat <-c("\\|[[:digit:]]\\.?[[:digit:]]?")
tpoints <- unlist(str_extract_all(chesstext, tpointspat))
tpoints <- as.numeric(gsub("\\|", "", tpoints))

#num seq
playernumber<- seq(1, 64)
```

#first look at df
```{r}
#chessdf with variables so far
chessdf <- data.frame(playernumber, name, state, prerating, tpoints)
#make a player number vector
chessdf <- as_tibble(chessdf)
chessdf
```


#steps to get the opponent data
```{r}
#opponent grid as dataframe
oppvec<-(str_extract_all(chesstext2, "[[:space:]][[:digit:]]{1,2}"))
oppvec[1:5]
oppdf<-plyr::ldply(oppvec, rbind)
oppdf <-oppdf[,-1]
colnames(oppdf) <- c("opp1", "opp2", "opp3", "opp4", "opp5", "opp6", "opp7")
oppdf<-apply(oppdf,2,function(x)gsub('\\s+', '',x))
oppdf[1:5,]
```



```{r}
#use lookup table to convert opponent numbers to opponent rating
lut <- data.frame(chessdf$playernumber, chessdf$prerating)
colnames(lut) <- c("pnum", "prating")
lut$pnum = as.character(as.numeric(lut$pnum))
lut$prating = as.character(as.numeric(lut$prating))
```

```{r}
#opponent rating dataframe
oppratingdf <- oppdf #make a copy
oppratingdf[is.na(oppratingdf)] <- 0
oppratingdf[] <- lut$prating[match(unlist(oppratingdf), lut$pnum)]
oppratingdf[1:16,]
oppratingdf<-as_tibble(oppratingdf)
oppratingdf$opp1<-as.numeric(oppratingdf$opp1)
oppratingdf$opp2<-as.numeric(oppratingdf$opp2)
oppratingdf$opp3<-as.numeric(oppratingdf$opp3)
oppratingdf$opp4<-as.numeric(oppratingdf$opp4)
oppratingdf$opp5<-as.numeric(oppratingdf$opp5)
oppratingdf$opp6<-as.numeric(oppratingdf$opp6)
oppratingdf$opp7<-as.numeric(oppratingdf$opp7)

```

```{r}
oppratingdf %>% 
  mutate(means=rowMeans(., na.rm=TRUE)) -> oppratingdf3
```  

```{r}
chessdf$avgopprating <- oppratingdf3$means
```

```{r}
print(tbl_df(chessdf), n=64)
```

#write to a csv
```{r}
chessdf %>% write.csv(.,file = "C:/Users/Matt/Documents/CUNY/DATA/PROJECT1/chessoutput.csv")
```

#create a histrogram of the avg opp rating
```{r}
hist(chessdf$avgopprating, xlab="Avg Opp Rating", main="Distribution of Avg Opponent Rating", col="lightgreen", xlim=c(1100,1700),  ylim=c(0, 25))
```
