---
title: "Project2Zillow"
author: "Matthew Baker"
date: "March 9, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(dplyr)
```


```{r}
#read in each file
zfile <- read.csv("https://raw.githubusercontent.com/mharrisonbaker/CUNYassignments/master/Project2/zillowdata.csv", header = TRUE)
```

#rename some columns
```{r}
zdata<-zfile
monthnames<-c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
names(zdata)[3:14]<-monthnames
head(zdata)
```

#take the top ten biggest states
```{r}
zdataL<-zdata %>% gather(Month, MedValue, Jan:Dec)
head(zdataL)
zdataL %>% filter(SizeRank<10) -> zdatatop 
head(zdatatop)
```

#this code produces the highest median sales value by month for each of the top 10 states 
```{r}
zdatatop %>% select(RegionName, Month, MedValue) %>% group_by(RegionName) %>% mutate(MedValue == max(MedValue)) %>% ungroup() ->bestmonth
bestmonth  <- bestmonth %>% rename(bestmonth=`MedValue == max(MedValue)`)
bestmonth %>% arrange(desc(bestmonth))
```